# Generated by Django 5.0.4 on 2024-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='building',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='faculty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
