# Generated by Django 5.0.4 on 2024-04-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roomitem_building_roomitem_faculty_roomitem_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomitem',
            name='building',
        ),
        migrations.RemoveField(
            model_name='roomitem',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='z',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='roomitem',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
