# Generated by Django 5.0.4 on 2024-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_roomitem_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
